# This is a basic workflow to help you get started with Actions

name: Bump version

on:
  push:
    branches:
      - dev

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GH_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          prerelease: alpha
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
